version: '3'
services:
    db:
        image: "mariadb"
        container_name: db
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/mysql
        ports:
        -   8083:3306
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
    asde8:
        image: "feikede/drupal8-docker"
        container_name: asde8
        restart: unless-stopped
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./publicfs:/var/www/html/web/publicfs
            - ./custom_modules:/var/www/html/web/modules/custom
            - ./custom_themes:/var/www/html/web/themes/custom
        ports:
            - 8081:80
        environment:
            DOCUMENT_ROOT: /var/www/html
            ENVIRONMENT: dev
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        environment:
            PMA_USER: root
            PMA_PASSWORD: mariadb
            PMA_HOST: db
        restart: unless-stopped
        links:
            - db
        ports:
            - 8082:80
